nfs:
  image: nfs
  # Required to load kernel NFS module
  privileged: true
  environment:
    - SHARED_DIRECTORY=/srv/data
  volumes:
    # NFS exports config
    - ./docker/nfs/exports:/etc/exports
    # Shares
    - /srv/data:/srv/data
  ports:
    - "111:111/tcp"
    - "111:111/udp"
    - "2049:2049/tcp"
    - "2049:2049/udp"
